entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

certificatesResolvers:
    letsencrypt:
        acme:
            email: "3xui-shop@example.com"
            storage: "acme.json"
            httpChallenge:
                entryPoint: web

providers:
    docker:
        exposedByDefault: false
